export enum ActionType {
  ADD_ROW = 'ADD_ROW',
  INSERT_ROW = 'INSERT_ROW',
  DELETE_ROW = 'DELETE_ROW',
  ADD_COLUMN = 'ADD_COLUMN',
  INSERT_COLUMN = 'INSERT_COLUMN',
  DELETE_COLUMN = 'DELETE_COLUMN',
  INSERT_CELL = 'INSERT_CELL'
}
